### ISSUE TITLE
how to incorporate erase-remove idiom?

### ISSUE THREAD

**Issue by glencornell** [klmr/multifunction#2]
Hi.  Awesome work!
I'm wondering how one would incorporate the [erase-remove idiom](https://en.wikipedia.org/wiki/Erase%E2%80%93remove_idiom) into the multifunction class.  My objective is to have a specialization of the multifunction template allow listeners to modify the container (add new or erase existing listeners).

I tried by replacing the following code in static R call_helper::call(...):

`for (auto listener : listeners)
          ret = listener(args...);
`
With the following:
`listeners.erase(std::remove_if(listeners.begin(),
                                       listeners.end(),
                                       [](std::function<R(Args...)> listener, Args... args){ return listener(args...); }),
                        listeners.end());
`
But to no avail.

**Comment by klmr** [comment]
I don’t quite understand what this is supposed to accomplish.

Adding and removing listeners is already supported in the container via `+=` and `-=`. In particular, there’s no need for the erase–remove idiom, and furthermore you code wouldn’t work, because
- `remove_if` takes as third argument either a _value_ to be removed, or a predicate (i.e. a unary function returning `bool`). You are trying to pass something else. Your code does neither.
- Removal requires modifying not just the `listeners` vector but also the `token_lookup` vector — for details, look at what `operator -=` does.

If your aim is to allow _listeners to remove themselves_, you need to think more carefully about the design:
- How will a listener signal that it wants to be removed?
- Will listeners have return values?
- Should this be a _general_ solution, i.e. should all listeners in principle be able to remove themselves?

At the moment, none of these considerations is accommodated in any way, and it isn’t clear how to design such a feature.

Of course, a listener can remove itself _if_ it has access to the original `multifunction` object reference, as well as its removal cookie. For instance, the following works:

``` cpp
#include <iostream>
#include <memory>
#include "multicast.hpp"

util::multifunction<void()> event;

void listener();

using cookie_t = decltype(event += listener);
std::unique_ptr<cookie_t> cookie;

void listener() {
    std::cout << "listener()\n";
    event -= *cookie; // Listener removes itself.
}

int main() {
    // Add listener, and store cookie in a pointer.
    cookie = std::unique_ptr<cookie_t>(new cookie_t{event += listener});
    event();
    event();
}
```

Admittedly, this is a bit convoluted because the “cookie” is deliberately an opaque type without default constructor, so its type needs to be captured via `decltype`, and it needs to be stored in a `unique_ptr`.
