### ISSUE TITLE
a question

### ISSUE THREAD

**Issue by jvdb66** [klmr/multifunction#4]
Hi all,
what is the function of:

        // Adjust token_lookup positions which have shifted.
        for (auto& token_index : token_lookup)
            if (token_index > i and token_index != NIL)
                --token_index;

in  void operator -=(function_token token)

**Comment by klmr** [comment]
Yeah that code could use some better commenting (and the logic is more convoluted than necessary, I think). The basic problem is that we unfortunately can’t directly delete listeners from a `multifunction`. The reason for this is simple: in order to find which listener to delete, we need to have a way of comparing equality. And C++ simply does not implement equality comparison for all kinds of callables (in particular, for lambdas).

That’s why `multifunction` uses a `token` type to identify a listener, and `-=` uses that token to remove a listener. The most straightforward implementation of a token would be as an index into the `listeners` vector. However, this would make the `call` helper function much less efficient because now we can’t simply iterate over the listeners and call them all in turn. Instead, we have to first check whether a given listener is still set or whether it has been removed (this code is pretty terrible: like the original implementation, which is purely a proof of concept, it doesn’t perform perfect forwarding etc.):

```cpp
R ret;
for (auto listener : listeners) {
    if (listener) ret = listener(args...);
}
return ret;
```

This innocuous-looking `if (listener)` conditional is a potential performance killer (in reality it’s probably not too bad since `std::function` has some overhead as well … but conceptually we really want to avoid this).

To avoid having “gaps” in the `listeners`, we therefore use two vectors: one that contains the actual listeners, and one, `token_lookup`, containing indices into the `listeners` vector. A token in turn is an index into that second `token_lookup` vector.

In the line immediately following the code you posted,

https://github.com/klmr/multifunction/blob/a19a2dd51d2436d830fb8cfb788a446a071f0ce5/multicast.hpp#L99

we delete the given listener from the vector of listeners. This `erase` call shifts all the following listeners forward by one. This means that all the indices inside `token_lookup` which are greater than the deleted listener’s index, now point to the wrong element and they all need to be shifted forward.

---

As mentioned above, this whole repository was a very quick proof-of-concept implementation and is by no means ideal. I am actually convinced that the token type is probably unnecessary and that, with a bit of thinking somebody could come up with a way of making the C# syntax work.

**Comment by jvdb66** [comment]
What about this code?
(no more class function_token)
(clear() clear all listener)



    template <typename F>
    std::size_t  operator +=(F listener) {
        listeners.push_back(listener);
        token_lookup.push_back(listeners.size() - 1);
        return token_lookup.size() - 1;
    }

    void operator -=(std::size_t unsubscribe_token) {

        if(listeners.size()==0) 
            return;

        if (unsubscribe_token >= token_lookup.size()) 
            return;

        auto i = token_lookup[unsubscribe_token];

        if (i == NIL)
            return;

        // Adjust token_lookup positions which have shifted.
        for (auto& token_index : token_lookup)
            if (token_index > i and token_index != NIL)
                --token_index;

        listeners.erase(listeners.begin() + i);
        token_lookup[unsubscribe_token] = NIL;
    }

    R operator ()(Args... args) const {
        return detail::call_helper<R, Args...>::call(listeners, args...);
    }

    void clear()
    {
        listeners.clear();
        token_lookup.clear();
    }

_usage:_

util::multifunction<void()> event;

auto id = e += ([]()
{
 printf("event1\r\n");
});

e();

e  -= id;

e  -= 5;  // failed

**Comment by klmr** [comment]
The issue with your code is precisely that the token is no longer an opaque type but rather an integer so you’ve lost type safety. It also makes the client code less clear: why does `+=` return an integer? What does it represent? Whereas a dedicated type answers this question: “`+=` returns an opaque token, you can’t do *anything* with it, except pass it to `-=` — so that’s what it’s used for).

**Comment by jvdb66** [comment]
Hi all,
I'm making an embedded framework and I plan to use your component (multifunction)
(stm32, freertos, gnu arm)
Code:
```c++
class ILifeCycle
{
    public:
        virtual void Init() = 0;

        virtual void Start() = 0;

        virtual void Stop() = 0;

        virtual void DeInit() = 0;
}

class Event : public LifeCycle
{
public:
    void Init()
    {}

    void DeInit()
    {}

    void GenerateEvent()
    {
        event(10);
    }

    util::multifunction<void(int)>& GetEvent()
    {
        return event;
    }

private:
    util::multifunction<void(int)> event;
};

class EventSubscriber : public LifeCycle
{
public:
    EventSubscriber(Event& e) : e(e)
    {}

    void Init()
    {
        id = e.GetEvent() += ([](int)
        {
            printf("event1\r\n");
        });
    }

    void DeInit()
    {
        e.GetEvent() -= id;
    }

private:
    Event& e;
    util::multifunction<void(int)>::function_token id;
};
```
Now I have 2 questions:
1)
When I compile the code I get 
Error 'util::multifunction<void (int)>::function_token': no appropriate default constructor available
(due to the opaque type)
How do I fix it?

2)
Operator += and -= require a mutex. Where do I put the mutex (I think call_helper)

**Comment by klmr** [comment]
It’s generally an [anti-pattern](https://stackoverflow.com/a/27184951/1968) in C++ (and [not just in C++](https://softwareengineering.stackexchange.com/a/334994/2366)) to have `Init` and `Deinit` functions: that’s what constructors and destructors are for! 

Once you use constructors, the problem vanishes:

```cpp
class EventSubscriber
{
    using handle_t = util::multifunction<void(int)>::function_token;

public:

    EventSubscriber(Event& e) : e(e), id{Subscribe()}
    {}

    ~EventSubscriber()
    {
        e.GetEvent() -= id;
    }

private:
    handle_t Subscribe()
    {
        return e.GetEvent() += ([](int)
        {
            printf("event1\r\n");
        });
    }

    Event& e;
    handle_t id;
};
```

---

Please note that I just pushed a few updates that make this project slightly more usable; for example, I finally implemented perfect forwarding. I also changed the obscure name `function_token` into the conventional name for such a class, `handle`.

**Comment by jvdb66** [comment]
That works!!
Thanks

**Comment by jvdb66** [comment]
Sorry
After git updating I get:

`error C2664: 'R util::multifunction<void (int)>::operator ()(int &&) const': cannot convert argument 1 from 'int' to 'int &&'`

What is wrong?

**Comment by klmr** [comment]
My mistake, apologies. I mucked up the perfect fowarding. It should be fixed now.

**Comment by jvdb66** [comment]
Thanks Konrad
